# Generated by Django 6.0.5 on 2026-05-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city_slug', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('djia_value', models.FloatField()),
                ('hash_value', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'city_slug')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('status', models.CharField(choices=[('going', 'Going'), ('interested', 'Interested')], default='going', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meetpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.meetpoint')),
            ],
            options={
                'unique_together': {('session_id', 'meetpoint')},
            },
        ),
    ]
